# Random Sampling with NumPy
## -To generate data like for OTP

In [1]:
import numpy as np
import random 


In [2]:
np.random.random()     ##Gives random no btween 0 and 1

0.8978627469988165

In [3]:
np.random.random((3,4))  ##2-d array of random nos btwn 0 and 1

array([[0.6657408 , 0.2880971 , 0.17071349, 0.66977332],
       [0.53947316, 0.19826567, 0.97951011, 0.35385454],
       [0.86599474, 0.5877536 , 0.14478097, 0.91112984]])

In [7]:
np.random.rand(3,4)

array([[0.97876728, 0.51874373, 0.66868155, 0.20134826],
       [0.48283488, 0.36169255, 0.11781627, 0.95505716],
       [0.34559349, 0.50757867, 0.76401613, 0.15138696]])

In [8]:
np.random.randn(3,4)    ##random no of normal distribution

array([[ 0.27108313,  0.15145796, -1.29035138, -1.55306374],
       [ 0.42682849, -0.46820765,  0.90352765, -0.35556142],
       [ 1.27570421,  0.45110432,  0.1376138 ,  0.31507987]])

In [4]:
np.random.randint(1,8)   ##random integer btwn 1 AND 7 (8 exclusive)

4

# random.seed(10) ensures ki har bar random sample wahi aaiye BC

In [65]:
np.random.seed(10)
np.random.randint(1,8,(4,3))###2-d array of random integers 

array([[2, 6, 5],
       [1, 2, 4],
       [5, 2, 6],
       [1, 6, 2]])

In [66]:
x=[1,2,3,4]
print(np.random.choice(x))

3


In [132]:

np.random.permutation(x)


array([3, 4, 1, 2])

# String Operations

In [135]:
str1 ="Indian AI"
str2 ="NumPy"
x=np.char.add(str1,str2)
print(x)
print(type(x))

Indian AINumPy
<class 'numpy.ndarray'>


In [136]:
np.char.lower(str1)

array('indian ai', dtype='<U9')

In [137]:
np.char.upper(str2)

array('NUMPY', dtype='<U5')

In [139]:
np.char.center(str1,60,fillchar='*')

array('*************************Indian AI**************************',
      dtype='<U60')

In [141]:
np.char.split(str1)

array(list(['Indian', 'AI']), dtype=object)

In [142]:
np.char.replace(str1,"AI","Artificial Intelligence")

array('Indian Artificial Intelligence', dtype='<U30')

In [145]:
np.char.count(str1,'i')

array(1)