# np.zeros() and np.ones()

In [2]:
import numpy as np

In [4]:
matrix_1 = np.array([[1,1,1],[1,1,1],[1,1,1]])


In [21]:
matrix_2 = np.ones((2,3),dtype =int)
print(matrix_2)

[[1 1 1]
 [1 1 1]]



# Go to paranthesis and SHIFT+Tab to get the argument of any function BC


In [15]:
mx_1s = np.ones(4,dtype=int) 
print(mx_1s)

[1 1 1 1]


In [17]:
mx_0s = np.zeros((4,6),dtype = int)
print(mx_0s)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]




# Empty Matrix me empty() fn se we get random values BC



In [19]:
mx_empty = np.empty((3,3),dtype=int)  
print(mx_empty)

[[ 191954088        404  628387695]
 [1937339228  862807412 1936874546]
 [1752065377 1819042862          0]]
