# NumPy = n-dimensional array


-Jaha numeric/scientific calculation wha NumPy ayega picture me BC


-Shift+Enter ya CTRL+Enter==RUN


-A=cell above B=cell below D+D=delete cell


-Kernel me jake restart and run all cell after repopening ipynb



In [1]:
import numpy as np
arr_1d = np.array([1,2,3,4])
print(arr_1d)
arr1d = [1,2,3,4]
print(arr_1d.dtype)


[1 2 3 4]
int32


In [2]:
print(type(arr_1d))
print(type(arr1d))
print(arr_1d)
print(arr1d)

<class 'numpy.ndarray'>
<class 'list'>
[1 2 3 4]
[1, 2, 3, 4]


In [3]:
arr_1d.ndim

1

# 2d array = lists of lists [[  ],[   ]]

In [10]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8]])

print(arr_2d)
print(arr_2d.size) #elements in array
print(arr_2d.ndim) #1-d/2-d/3-d array
print(arr_2d.shape)#(#rows,#columns)
print(arr_2d.dtype)

[[1 2 3 4]
 [5 6 7 8]]
8
2
(2, 4)
int32


In [5]:
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


# 3d array = lists of lists [[[    ],[    ]],[[   ],[   ]],[[   ],[   ]]]

In [9]:
arr_3d = np.array([[[1,1],[0,0]],[[0,0],[3,3]]])
print(arr_3d)
print(arr_3d.size) #elements in array
print(arr_3d.ndim) #1-d/2-d/3-d array
print(arr_3d.shape)#(#rows,#columns)
print(arr_d.dtype)

[[[1 1]
  [0 0]]

 [[0 0]
  [3 3]]]
8
3
(2, 2, 2)
int32


In [ ]:
np.array()